export const STATUSES = {
  STATUS_OK: 200,
  ERROR_BAD_EXCEPTION: 400,
  ERROR_UNAUTHORIZED: 401,
  ERROR_FORBIDDEN: 403,
  ERROR_NOT_FOUND_EXCEPTION: 404,
  ERROR_CONFLICT_EXCEPTION: 409,
  ERROR_VALIDATION_EXCEPTION: 422,
  ERROR_LINK_EXPIRED: 410,
  ERROR_TOO_MANY_REQUEST: 429,
  ERROR_INTERNAL_SERVER: 500,
}
